//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::products::Entity as Products;
pub use super::users::Entity as Users;
pub use super::product_template::Entity as ProductTemplate;