//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Deserialize, Serialize)]
#[sea_orm(table_name = "product_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sequence: Option<i32>,
    pub categ_id: i32,
    pub uom_id: i32,
    pub uom_po_id: i32,
    pub company_id: Option<i32>,
    pub color: Option<i32>,
    pub create_uid: Option<i32>,
    pub write_uid: Option<i32>,
    pub r#type: String,
    pub service_tracking: String,
    pub default_code: Option<String>,
    #[sea_orm(column_type = "JsonBinary")]
    pub name: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_purchase: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_sale: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub product_properties: Option<Json>,
    pub list_price: Option<Decimal>,
    pub volume: Option<Decimal>,
    pub weight: Option<Decimal>,
    pub sale_ok: Option<bool>,
    pub purchase_ok: Option<bool>,
    pub active: Option<bool>,
    pub can_image_1024_be_zoomed: Option<bool>,
    pub has_configurable_attributes: Option<bool>,
    pub is_favorite: Option<bool>,
    pub create_date: Option<DateTime>,
    pub write_date: Option<DateTime>,
    pub sale_delay: Option<i32>,
    pub tracking: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub responsible_id: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub property_stock_production: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub property_stock_inventory: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_picking: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_pickingout: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_pickingin: Option<Json>,
    pub is_storable: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub property_account_income_id: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub property_account_expense_id: Option<Json>,
    pub lot_valuated: Option<bool>,
    pub service_type: Option<String>,
    pub sale_line_warn: String,
    pub expense_policy: Option<String>,
    pub invoice_policy: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sale_line_warn_msg: Option<String>,
    pub country_of_origin: Option<i32>,
    pub hs_code: Option<String>,
    pub website_id: Option<i32>,
    pub website_size_x: Option<i32>,
    pub website_size_y: Option<i32>,
    pub website_ribbon_id: Option<i32>,
    pub website_sequence: Option<i32>,
    pub base_unit_id: Option<i32>,
    pub website_meta_og_img: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub website_meta_title: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub website_meta_description: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub website_meta_keywords: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub seo_name: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub website_description: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub description_ecommerce: Option<Json>,
    pub compare_list_price: Option<Decimal>,
    pub is_published: Option<bool>,
    #[sea_orm(column_type = "Double", nullable)]
    pub rating_last_value: Option<f64>,
    #[sea_orm(column_type = "Double")]
    pub base_unit_count: f64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub out_of_stock_message: Option<Json>,
    pub allow_out_of_stock_order: Option<bool>,
    pub show_availability: Option<bool>,
    #[sea_orm(column_type = "Double", nullable)]
    pub available_threshold: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
